### ISSUE TITLE
Use registry-url

### ISSUE THREAD

**Issue by rstacruz** [rstacruz/pnpm#10]
https://www.npmjs.com/package/registry-url

```js
var registryUrl = require('registry-url')

function registryUrlFor (package) {
  if (package.substr(0, 1) === '@') {
    return registryUrl(package.split('/')[0])
  } else {
    return registryUrl()
  }
}

registryUrlFor('@foo/bar') //=> registryUrl('@foo') => 'https://registry.foo.io'
```

This will be useful for private scoped modules support. See #9 @indexzero

**Comment by rstacruz** [comment]
ah yes, like #13 says, this will also allow you to specify npm registries via `npm config set registry https://my.registry.com`.

**Comment by indexzero** [comment]
@rstacruz interesting. What are your thoughts on unit testing? I was thinking about doing a spike on coverage and unit test coverage before doing too many more new features.

**Comment by rstacruz** [comment]
yes that'd be great! mostly i've been too lazy haha, the integration tests work really fast and covers most everything

**Comment by rstacruz** [comment]
there's a whole bunch of new features btw, just did a spike for a few hours. we now have compiled modules support (yay!) and improved reliability (you can cancel and resume `pnpm i` any time).

**Comment by fengmk2** [comment]
Can add support for `pnpm install --registry=http://registry.my.com` too? I want to help impl this feature.

**Comment by rstacruz** [comment]
using registry-url will get you this for free:

```js
env npm_registry=http://my.regsitry.com pnpm install
```

**Comment by rstacruz** [comment]
okay, lemme do it now :P

**Comment by rstacruz** [comment]
out in v0.11.1. upgrade!

**Comment by fengmk2** [comment]
Great!
