### ISSUE TITLE
Getting this weird error

### ISSUE THREAD

**Issue by jpalala** [rstacruz/pnpm#103]
Anyone know how to fix this:

fs.js:984
  binding.chown(pathModule._makeLong(path), uid, gid, req);
            ^
TypeError: uid must be an unsigned int
    at TypeError (native)
    at fs.chown (fs.js:984:11)
    at /usr/local/lib/node_modules/pnpm/node_modules/tar-fs/index.js:215:7
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by rstacruz** [comment]
What os/node versions?

**Comment by jpalala** [comment]
I couldn't reproduce it. The steps I remember taking a repo folder, moving it, then copying it back to a dir. 

Something like this:

https://www.dropbox.com/s/iazbdx0ilmnz09k/Screen%20Shot%202016-02-09%20at%204.30.20%20PM.png?dl=0

Anyway thanks!



Closing this issue, anyway, i'll reopen if ever i find a way to reproduce it.
