### ISSUE TITLE
Acknowledge "always_auth" and "_authToken"

### ISSUE THREAD

**Issue by brianreavis** [rstacruz/pnpm#105]
(for usage with private registries)
```sh
# .npmrc
always_auth = true
//<host>/:_authToken=<token>
```

Relevant: http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules

**Comment by adriantoine** [comment]
+1

**Comment by zkochan** [comment]
Hey @leipert, has your pull request resolved this one as well? I am not sure what `always_auth=true` means

**Comment by leipert** [comment]
Yeah, it should work.
If your using the public npm registry, you do not need auth for [GET requests](https://docs.npmjs.com/misc/config#always-auth).
But pnpm actually sets the token on [each request](https://github.com/rstacruz/pnpm/blob/master/lib/got.js#L74-L82) which goes to a `https://` registries, so `always_auth` is per se `true` when using pnpm and having saved credentials.

**Comment by zkochan** [comment]
Awesome! Thanks!
