### ISSUE TITLE
issue with installing exec-time: hosted packages not supported

### ISSUE THREAD

**Issue by jpalala** [rstacruz/pnpm#106]
I was using pnpm to install exec-time and got this:

``` 
exec-time git+https://github.com/capablemonkey/exec-time#e39279713fcb87a9c9e27f5a81d913d7b6853c3d ERROR ✗ 
  mocha 1.21                                                      finding · 
  underscore 1.6.0                                                finding · 
```

> ! git+https://github.com/capablemonkey/exec-time#e39279713fcb87a9c9e27f5a81d913d7b6853c3d: hosted packages not supported

**Comment by iamstarkov** [comment]
it's because hosted packages are not supported

**Comment by rstacruz** [comment]
indeed, hosted packages aren't supported.

**Comment by iamstarkov** [comment]
but they are in roadmap https://github.com/rstacruz/pnpm/blob/master/docs/roadmap.md

**Comment by jpalala** [comment]
Ok gotcha
