### ISSUE TITLE
Looks like pnpm does not build fsevents in chokidar on osx

### ISSUE THREAD

**Issue by istarkov** [rstacruz/pnpm#119]
OSX, node 5.x

The problem:
`chokidar` installed with pnpm uses polling not fsevents

Problem example project:
https://github.com/istarkov/pnpm_polling

Details:

Run this script if chokidar installed with pnpm

```
var chokidar = require('chokidar');
chokidar.watch('.', {ignored: /[\/\\]\./}).on('all', (event, path) => {
  console.log(event, path);
});
```

Check fsevents

```
sudo fs_usage -f . -w | grep node
```

There will be a lot of node events (and script takes 100% CPU)

This issue is not exists with npm

**Comment by patrickheeney** [comment]
It looks like fsevents is an optional dependency https://github.com/paulmillr/chokidar/blob/master/package.json#L42 so you would have to install that into your project for it to be used. `pnpm install fsevents --save-dev`.

**Comment by istarkov** [comment]
You are right, thank you!!!
