### ISSUE TITLE
'symlink install' make React Native error

### ISSUE THREAD

**Issue by yujiangshui** [rstacruz/pnpm#120]
Like this demo: https://github.com/yujiangshui/react-web-example.

When I use `npm install`, it will be:

![qq20160218-1 2x](https://cloud.githubusercontent.com/assets/2942913/13147957/1a26be7a-d696-11e5-845e-f9000ef6b5b0.png)

But when I run `pnpm install`, it will be:

![qq20160218-0 2x](https://cloud.githubusercontent.com/assets/2942913/13147963/21ef3da8-d696-11e5-8864-970a36af9011.png)

And react native will use the wrong path then show error:

![qq20160218-2 2x](https://cloud.githubusercontent.com/assets/2942913/13147965/23f9e936-d696-11e5-94c3-6ebf2861b16f.png)

**Comment by patrickheeney** [comment]
`pnpm` doesn't flatten the directory in `node_modules`, but rather in `node_modules/.store` so the folders will definitely look different. I don't believe `react-native` packager supports symlinks yet so you will most likely need to explore the workarounds in facebook/react-native/issues/637.

**Comment by yujiangshui** [comment]
@patrickheeney Thanks for your infomation.
