### ISSUE TITLE
pnpm should not fail hard on local packages

### ISSUE THREAD

**Issue by patrickheeney** [rstacruz/pnpm#121]
Until local packages are supported, `pnpm` should warn and skip these dependencies. Currently, `pnpm` is unusable if you have local packages and are required to manually delete / restore just to get it to work.

**Comment by patrickheeney** [comment]
Same thing for hosted packages:

```
  bootstrap git@github.com:twbs/bootstrap.git#v4.0.0-alpha.2        ERROR ✗

 ! git@github.com:twbs/bootstrap.git#v4.0.0-alpha.2: hosted packages not supported
```

I can manually install it into the .store and symlink if `pnpm` does not fail hard and instead just warns.

**Comment by zkochan** [comment]
These packages should not fail anymore because they are supported
