### ISSUE TITLE
Add a public API for installation and linking

### ISSUE THREAD

**Issue by patrickheeney** [rstacruz/pnpm#125]
I am using pnpm as part of a mono repo and I need to install a subset of the package.json files. Something like `pnpm install -f package.local.json`. Since files are not supported, I looked at integration within my own CLI tool. These are the problems I ran into:

```javascript
const install = require('pnpm/lib/cmd/install');
const installError = require('pnpm/lib/err');

return install(dependencies, { quiet: false }).catch(installError);
```

On the surface, this looks pretty good, but it unfortunately uses the `package.json` from the current directory of my CLI tool as root, so it installs them in the wrong location.

```javascript
const install = require('pnpm/lib/install_multiple');
const installConfig = require('pnpm/lib/config');
const installLog = require('pnpm/lib/logger');
const installError = require('pnpm/lib/err');
const installPeers = require('pnpm/lib/install/link_peers');

const ctx = {
  root: rootPath,
  store: path.resolve(rootPath, installConfig.store_path),
  log: installLog()
};
    
return install(ctx, dependencies, path.join(ctx.root, 'node_modules'), { quiet: false })
  .then(_ => installPeers(null, ctx.store, ctx.installs))
  .catch(installError);
```

This did the trick, but as you can see its pretty verbose and reaches quite a bit into the `pnpm` internals. It would be nice to have a public API that could do something like this:

```javascript
import pnpmApi from 'pnpm/api';

return pnpmApi.install(dependencies, rootPath, { quiet: false });
```

The implementation would look like my last snippet above. Let me know if you would accept a pull request for this?

EDIT: Also wanted to point out that `installPeers` accepts `pkg` as a first argument, but it does not use it in the function.

**Comment by rstacruz** [comment]
ah, neat! I don't think making a separate `pnpm/api` is the way to go here... i think it's best we make `install()` take the things you need—less code paths to maintain.

**Comment by davej** [comment]
@patrickheeney looks good, only thing I would add is that it would be nice if it exposed an EventEmitter to track progress rather than logging to console. Perhaps even better might be a generator but that could be more difficult to implement.

**Comment by davej** [comment]
@zkochan: Finally got around to using this API. Works nicely! Only thing that is missing (IMO) is to return the installed package's info. So, for example, I could find out which version was actually installed.

**Comment by zkochan** [comment]
Shouldn't be hard to do it. [Here](https://github.com/rstacruz/pnpm/blob/master/src/api/install.ts#L151-L153) that info is being written to the [store.json](https://github.com/rstacruz/pnpm/blob/master/docs/store-json.md). So we can get it from storeJson.dependents[installPkgName]
