### ISSUE TITLE
pnpm install inside ember-cli/ember-cli repo errors

### ISSUE THREAD

**Issue by stefanpenner** [rstacruz/pnpm#132]
It appears running `npm install` inside `ember-cli/ember-cli` must be run severalj times to complete successfully

first error:

```
 ! ENOENT: no such file or directory, open '/Users/stefanpenner/src/ember-cli/node_modules/.store/mdurl@1.0.1/_/package.json'
```

second error:

```
 ! ENOENT: no such file or directory, open '/Users/stefanpenner/src/ember-cli/node_modules/.store/string_decoder@0.10.31/_/package.json'
```

then it usually works.

**Comment by stefanpenner** [comment]
Also, it appears sometimes it also works first try..

**Comment by thangngoc89** [comment]
Related to this. https://github.com/rstacruz/pnpm/issues/122

Happens all the time, randomly

**Comment by stefanpenner** [comment]
Seems to be resolved, will reopen if I see it again.
