### ISSUE TITLE
Tracking install progress when using programmatically

### ISSUE THREAD

**Issue by davej** [rstacruz/pnpm#139]
I'm using `pnpm` programmatically with a project I'm working on. It would be nice to be able to track install progress somehow but at the moment it looks like progress is just logged directly to the console.

I'm happy to do a PR for this if you think it's a good idea. What do you think is a good way to expose this information? An event emitter or something? Ideally a generator would be an awesome interface but that would be quite an overhaul and may have performance/compatibility implications.

I was thinking it may be enough to take an option which would redirect logger input to a public event emitter for third-parties to subscribe to. Might not be the ideal approach but shouldn't be difficult to implement.

**Comment by davej** [comment]
Actually I'm not sure this is necessary as I can just provide a custom log function from the `ctx` object when using `lib/install`. Feel free to close this.

**Comment by patrickheeney** [comment]
Related to #125 . I would be interested to see how you are using it and would love your input on the API to support this.

**Comment by davej** [comment]
@patrickheeney something like this:

```js
import install from 'pnpm/lib/install';
import save from 'pnpm/lib/save';

const ctx = {
   root: PROJECT_DIR,
   store: join(PROJECT_DIR, 'node_modules/.store'),
   // Provide your own log function to track progress
   log: (a, b) => (c, d) => console.log(a, b, c, d)
 };

 install(ctx, 'some-package', join(PROJECT_DIR, 'node_modules'))
   .then(dep =>
     save({ path: PROJECT_DIR + 'package.json' }, [dep], 'dependencies')
       .then(() => {
         // 'some-package' installed and saved as dep in package.json
       })
   );
```

**Comment by rstacruz** [comment]
Nice one guys! Yes this is precisely why ctx.log is exposed.

**Comment by ecstrema** [comment]
I can't seem to find the documentation for the public API. Is it documented somewhere?
