### ISSUE TITLE
Where is help wanted?

### ISSUE THREAD

**Issue by davej** [rstacruz/pnpm#14]
Rather than jump into a random feature, are there any discrete chunks of functionality that you would appreciate PRs for?

**Comment by rstacruz** [comment]
issues, #10 is easy! and the todo list at https://github.com/rstacruz/pnpm#preview-release — keep in mind at this point pnpm is still to early though, many things are likely to change.

there's also https://github.com/alexanderGugel/ied which can also appreciate some contributor love.

**Comment by rstacruz** [comment]
Okay, I added a help wanted tag, let's do this
