### ISSUE TITLE
Uninstall support

### ISSUE THREAD

**Issue by davej** [rstacruz/pnpm#144]
Hey @rstacruz, I'm up for implementing `pnpm uninstall` support.

Could you give me a top-down view of what needs to be done and if there are any gotchas that I need to look out for?

**Comment by zkochan** [comment]
I think I know how to do it.

The only gotcha is to remember that stores can be shared between several packages. The symlink in the package's `node_modules` can be deleted immediately but from the `.store` only if no other packages inside or outside of the store are dependent on it.

A `store.json` in the root of the store folder could contain a dictionary with information about which packages depend on which packages. E.g.

```
{
  "foo@1.2.3": [
    "bar@0.3.0"
  ]
}
```

This means that `bar@0.3.0` is dependent on `foo@1.2.3`. `foo@1.2.3` cannot be deleted till it has dependents.

**Comment by davej** [comment]
@zkochan awesome!
