### ISSUE TITLE
[Feature] Verbose mode for debug

### ISSUE THREAD

**Issue by PeterDaveHello** [rstacruz/pnpm#179]
Is it possible to provide a verbose mode for debug?
I don't know what's the reason why pnpm doesn't work on my certain computer, tried with several node versions, but npm works fine. Thanks.

```
peter@peter ~/ $ pnpm i aframe-text-component
  aframe-text-component                                             ERROR ✗ 

tunneling socket could not be established, cause=Parse Error
GET registry.npmjs.org/aframe-text-component
```

**Comment by rstacruz** [comment]
There's already --debug, you can try that one.

**Comment by PeterDaveHello** [comment]
Thanks, seems it's not in the help message, will try now.

**Comment by rstacruz** [comment]
Yeh, it seems like something only pnpm developers would be interested in so
it wasn't documented :-)

**Comment by PeterDaveHello** [comment]
I try to add it in #180, is it acceptable? I'll be good to have it in the help message :)

**Comment by zkochan** [comment]
Seems like this one was merged and published, so I am closing this issue.

**Comment by Yaojian** [comment]
Today's `pnpm help install` shows

```
Output:
      --reporter append-only       The output is always appended to the end. No cursor manipulations are performed
      --reporter default           The default reporter when the stdout is TTY
      --reporter ndjson            The most verbose reporter. Prints all logs in ndjson format
  -s, --silent, --reporter silent  No output is logged to the console, except fatal errors
```

Just a note who googled this issue like me ^_^.
