### ISSUE TITLE
Add one more layer in .store for prod vs dev (vs others?)

### ISSUE THREAD

**Issue by mhart** [rstacruz/pnpm#2]
This makes it possible to add a single `dev` (or `prod`) directory to a .gitignore, or a .dockerignore, or similar.

Currently with the flat hierarchy there's no delineation between prod and dev deps (same problem in npm3 tbh: https://github.com/npm/npm/issues/9674 )

Deduping will perhaps be more difficult, so I get this is a big ask.

**Comment by rstacruz** [comment]
seems like an interesting idea, but i'm wondering: what would be the practical use case of separating dev and prod dependencies?

**Comment by mhart** [comment]
.gitignore as well – for when you want to check your prod dependencies in to git, but not your dev dependencies. I'm sure there are other ".ignore" files that could benefit from this too.

Any time you want to tar up / archive your project to transfer or deploy it anywhere else, basically.

There's an argument to be made that it makes it easier to navigate from a filesystem perspective – when you want to debug your modules, etc – you know you just need to worry about what's in the prod dir.

**Comment by rstacruz** [comment]
Interesting, but this is a lot more nuanced than it seems on the surface. What if both your prod and dev dependencies use `is-array@1.0.1`, shouldn't it be present in both layers? which one gets precedence over the other?

I'd wait to see what npm comes up with to solve that solution. As they mentioned in https://github.com/npm/npm/issues/9674, they're looking into it. I'm sure they're more knowledgeable about the ins and outs of this problem and the possible corner cases there can be.

Thanks for the report!

**Comment by jonathanong** [comment]
i prefer the tarballs to be stored globally, but i'd always want the actually packages to be unzipped and compiled within the module. otherwise, if something fucks up, i'd have to clear the global cache.

**Comment by mhart** [comment]
@rstacruz prod would always take precedence over dev in that case

Agreed though, probably better to wait to see how npm's plan pans out.

@jonathanong I'm not sure what you're referring to?

**Comment by rstacruz** [comment]
> i prefer the tarballs to be stored/cached globally, but i'd always want the actual packages to be unzipped and compiled within the current module. otherwise, if something fucks up, i'd have to clear the global cache.

it seems this is the only way to go right now: https://github.com/rstacruz/pnpm/issues/19#issuecomment-177007860

**Comment by zkochan** [comment]
@mhart, we are currently working together with ied on some shared store specs. You can review the specs and add your suggestions. https://github.com/alexanderGugel/ied/blob/spec/spec/STORE.md
