### ISSUE TITLE
Is it possible throw hosted packages to official npm?

### ISSUE THREAD

**Issue by PeterDaveHello** [rstacruz/pnpm#210]
I'm wondering if this is an acceptable idea that we just throw hosted packages to official npm, instead of just exit the install process? 

BTW, this project is awesome, thanks a lot!

**Comment by andreypopp** [comment]
What do you mean by hosted packages, @PeterDaveHello?

**Comment by PeterDaveHello** [comment]
on GitHub? It's the wording from pnpm's output, I'm not sure the precise wording.

**Comment by andreypopp** [comment]
GitHub hosted packages are supported. What's pnpm version are you using?

**Comment by PeterDaveHello** [comment]
It's a "28 May" opened issue, I'm using the latest pnpm now and didn't install a hosted package recently, I'll try it later, thanks!

**Comment by martinsik** [comment]
I think you mean packages fetched from git. For example:

```
"dependencies": {
    "my-package": "git+ssh://git@bitbucket.org/company/my-package.git"
}
```

This will be rejected with:

```
$ ./node_modules/.bin/pnpm i
  company/my-package git+ssh://git@bitbucket.org/company/my-package.git      ERROR ✗ 

 ! git+ssh://git@bitbucket.org/company/my-package.git: hosted packages not supported
```

I guess this is mentioned in [https://github.com/rstacruz/pnpm/blob/master/docs/roadmap.md](roadmap.md) under `git-hosted packages` which is still unchecked.

Btw, `pnpm` version:
```
$ ./node_modules/.bin/pnpm -v
0.31.1
```

**Comment by zkochan** [comment]
Support for git hosted packages was added in [v0.35.0](https://github.com/rstacruz/pnpm/releases/tag/v0.35.0).

**Comment by PeterDaveHello** [comment]
Thanks @zkochan
