### ISSUE TITLE
Possibility to configure "store_path" on command line or globally

### ISSUE THREAD

**Issue by tomitrescak** [rstacruz/pnpm#214]
What a fantastic project!!!! I managed to reduce my codebase from >800.000 files to <15.000 and size from 32GB to  matter of few megabytes.

I did it by creating a global store located in my home directory and chasing the config/store_path to '/User/myuser/.store'

1. Do you reckon it is a good practice? It works like charm!
2. Would you consider to have the possibility to change the configuration on the command line or set it globally, so that I do not have to fork the whole project just to change that config line?

Thanks a lot and KUDOS!!!

**Comment by zkochan** [comment]
I think this is now possible that NodeJS v6.3.0 introduced the `--preserve-symlinks` option. However, at least this should be implemented first: [Preserve symlinks on Node.js >=v6.3.0](https://github.com/rstacruz/pnpm/issues/244)

**Comment by leipert** [comment]
`store_path` should be changed to `storePath`.

[pnpm camelcases all the keys](https://github.com/rstacruz/pnpm/blob/master/bin/pnpm-install#L69) from the .rc files, so it is not possible to set the storepath in an `.npmrc` or `.pnpmrc`

Steps to reproduce: 

1. Set `store_path` in the `.npmrc`, 

	```
	store_path=node_modules/.pnpm-store
	```
2. See how pnpm ignores the parameter 😅

**Comment by zkochan** [comment]
oh, I am sorry, I've broken it when making pnpm use the npmrc configs. However, this is not release yet. I can fix it this evening.

Also I think the config key should be renamed to `store-path` to match the npm config conventions.

**Comment by leipert** [comment]
no problemo 👍 
thanks for the good work

**Comment by tomitrescak** [comment]
Where is the .npmrc located?

**Comment by zkochan** [comment]
Either globally, in the npm folder, or in the root folder of your package, or in any parent directory

**Comment by zkochan** [comment]
More about shared store here: https://github.com/rstacruz/pnpm/blob/master/docs/recipes/shared-store.md

**Comment by dandv** [comment]
Where the current documentation about a shared store? https://pnpm.js.org/docs/en/about-package-store.html doesn't mention anything about it. My use case is that I want to share the same store across two volumes in Linux.
