### ISSUE TITLE
Scoped packages

### ISSUE THREAD

**Issue by tomitrescak** [rstacruz/pnpm#219]
Hello, how difficult would it be to add support for scoped packages? For example: @kadira/storybook

**Comment by tomitrescak** [comment]
You seem to download packages just fine, but they get stuck in the .tmp folder.

**Comment by rexxars** [comment]
Since the latest release, installing a single scoped package works fine. It seems to have problems with multiple files from the same scope, however, getting errors such as:

```
 ! ENOENT: no such file or directory, symlink '../_' -> '<project-dir>/node_modules/.tmp/8a8f44c3-5f1d-4054-b30c-a6ab22dc94c3/node_modules/@sanity/router'
```

Any ideas, @rstacruz? I guess I could try to set up a few public scoped packages if you want to try to reproduce/fix?

**Comment by rexxars** [comment]
Seems like it works fine even for two dependencies, as long as they are defined in the same project. The problem seems to be when package `a` depends on `b`, which in turn depends on `c`. At least that's my working theory so far.

**Comment by zkochan** [comment]
I have an issue when installing dependencies in this package: [mos-plugin-example](https://github.com/mosjs/mos/tree/725ec528da6dafe98b45898b8983340dff29ff27/packages/mos-plugin-example)

It has a dependency on [independent](https://github.com/zkochan/independent) which has a dependency on this scoped package [@zkochan/async-replace](https://github.com/zkochan/async-replace)

The error I'm getting is 

```
! ENOENT: no such file or directory, symlink '../_' -> '/home/zoltan/src/mos/packages/mos-plugin-example/node_modules/.tmp/f448d627-ae48-48f9-be69-aa3cc4eb9b4/node_modules/@zkochan/async-replace'
```

**Comment by zkochan** [comment]
I've made it easier to reproduce. Try 'pnpm i -S test-pnpm-issue219'
