### ISSUE TITLE
--global

### ISSUE THREAD

**Issue by rstacruz** [rstacruz/pnpm#22]
```
npm install -g bower
```

Don't know how to do this yet... need to investigate.

`npm prefix -g` will show you where node modules are installed globally. Should pnpm dump things into `$(npm prefix -g)/lib/node_modules`? what about Windows?

How can `npm prefix -g` be obtained programatically?

[ied](https://github.com/alexanderGugel/ied) dumps your globals into ~/.node_modules, I believe. Not sure on what the pros and cons of that are at the moment, though.

**Comment by rstacruz** [comment]
let's not do --global. use npm for that :-)

**Comment by shouze** [comment]
@rstacruz I have a use case that would lead pnpm to manage global installs anyway.

If you use docker containers, the only way ATM to have node_modules located outside of your project/app source code is global install (not a big problem as you're running a dedicated container for you app). This trick permit to mount a shared volume of your source code during your local development process without the pain & slowness of shared volumes during node modules installs.

So, if I can help in any way to make global installs into pnpm a reality tell me what to do. There's also a `---prefix` option related to this feature I guess, no?

**Comment by reubano** [comment]
Any way you can provide a better error message? I just `pnpm install -g coffee-lint` today and got this:

` ! The package's modules are from store at /Users/reubano/.pnpm/node_modules/.store and you are trying to use store at /Users/reubano/.pnpm/.store/nested`

Not very useful IMHO.

**Comment by iamstarkov** [comment]
@reubano message is not that bad, but its not that good either. @zkochan might can help

**Comment by zkochan** [comment]
@reubano I created an issue for it to not forget

https://github.com/rstacruz/pnpm/issues/495

**Comment by reubano** [comment]
Thanks @zkochan!
