### ISSUE TITLE
pnpm install does not expose all packages in node_modules

### ISSUE THREAD

**Issue by nielsvermaut** [rstacruz/pnpm#230]
When running pnpm install, all packages get installed in the .store folder, but they don't get symlinked to the node_modules folder, which results in packages not being found in node scripts.

I've included my package.json and folder struct in a gist, to help you find the issue.

https://gist.github.com/nielsvermaut/295ae0c39196b0fd5eb5ff0df1d05f84

**Comment by iamstarkov** [comment]
@nielsvermaut what kind of node scripts do you have?

**Comment by nielsvermaut** [comment]
@iamstarkov kind of off topic, but it fails in my gulp file with gulp-util.

**Comment by iamstarkov** [comment]
That's not off topic, 'cause I didn't have issues with this and pnpm. Thank you

**Comment by nielsvermaut** [comment]
@iamstarkov I didn't want to come accros as rude, apologies if I did. I just can't see why my packages would be specific to this problem.

**Comment by andreypopp** [comment]
Can't repro, I used your `package.json` and this is what I got:
```
array-difference
babel-core
babel-polyfill
babel-preset-es2015
babel-preset-es2015-ie
babel-preset-react
babelify
bower
browserify
browserify-global-shim
caret-position
chunk-array
classnames
compose-dataset-shim
custom-event-polyfill
elasticlunr
email-validator
fuse.js
fy-shuffle
gulp
gulp-babel
gulp-bower
gulp-browserify
gulp-chown
gulp-concat
gulp-concat-css
gulp-debug
gulp-hologram
gulp-livereload
gulp-notify
gulp-rename
gulp-sass
gulp-sourcemaps
gulp-svgmin
gulp-svgstore
gulp-uglify
gulp-uglifycss
gulp-util
he
knuth-shuffle
moment
node-sass
object-array-converter
object-to-array
qwery
react
react-addons
react-dom
react-spawner
reactify
reqwest
run-sequence
scriptjs
split-array
vinyl-source-stream
```

pnpm as of 0.21.0

**Comment by zkochan** [comment]
@nielsvermaut what OS were you using? Was it a Windows?

**Comment by nielsvermaut** [comment]
It was on a Linux build server. I'll try to provide some more details tomorrow, because I cannot access it right now.

**Comment by zkochan** [comment]
@nielsvermaut are you still able to reproduce this issue?

**Comment by zkochan** [comment]
@nielsvermaut I think this might be fixed by the [flat tree](https://github.com/rstacruz/pnpm/issues/403) feature. Try to install `pnpm@next` and run `pnpm install --flat-tree`. pnpm will emulate a npm@3 flat tree

**Comment by zkochan** [comment]
Not reproducible on pnpm@0.47.0
