### ISSUE TITLE
Preserve symlinks on Node.js >=v6.3.0

### ISSUE THREAD

**Issue by zkochan** [rstacruz/pnpm#244]
Node.js v6.3.0 introduced a new option `--preserve-symlinks` that allows to make node resolve dependencies based on the symlinks location, not the realpath (read more: https://github.com/nodejs/node/issues/3402)

This new feature makes it possible to use a global store for pnpm and as a consequence to greatly reduce the disk space needed for dependencies. (a discussion about this was here: https://github.com/rstacruz/pnpm/issues/19)

However, the preserve symlinks feature is disabled by default and should be passed to node every time. E.g., `node --preserve-symlinks index.js`. As a consequence, executable in `node_modules/.bin` will not be executed with the `--preserve-symlinks` option.

## Proposed changes

(node: I suggest to make these changes on top of https://github.com/rstacruz/pnpm/issues/242)

The executables in `.bin` can be forced to run with `--preserve-symlinks` by

1. changing the shebangs to pass the `--preserve-symlinks` option to node
2. changing them from symlinks to proxy-files (real files that require the bin files from the symlinked package). E.g.:

  ```js
  #!/bin/sh
  ":" //# comment; exec /usr/bin/env node --preserve-symlinks "$0" "$@"

  require('../eslint/bin/eslint')
  ```

3. making executables from the proxy-files. E.g. `chmod 755 node_modules/.bin/eslint`

**Comment by rstacruz** [comment]
Thanks, that's pretty interesting. Just to note, this won't work on all packages; `mocha` is one example that works a little differently :)
