### ISSUE TITLE
support basic authorization

### ISSUE THREAD

**Issue by leipert** [rstacruz/pnpm#270]
Hey there.
We are using a private registry which just supports basic authorization. During our tests against this registry we could not download packages.

Unfortunately you [do not support Basic Authorization](https://github.com/rstacruz/pnpm/blob/master/lib/got.js#L79).

If you want, I could help you implement this (as we need it). Before I dig into it and creating a PR, I would like to know what is the best way to assist you with that feature.

FYI: [relevant parts in npm](https://github.com/npm/npm/blob/master/lib/config/get-credentials-by-uri.js)

My `.npmrc` file looks like this:
```
//registry.npmjs.org/:_authToken=TOKEN

registry=https://example.com/npm/

@npm:registry=https://example.com/npm/
//example.com/npm/:_password=PASSWORD
//example.com/npm/:username=username
//example.com/npm/:email=username@example.org
//example.com/npm/:always-auth=true

@npm-internal:registry=https://example.com/npm-internal/
//example.com/npm-internal/:_password=PASSWORD
//example.com/npm-internal/:username=username
//example.com/npm-internal/:email=username@example.org
//example.com/npm-internal/:always-auth=true
```

**Comment by zkochan** [comment]
Hey @leipert,
I think you have to make a pull request to [registry-auth-token](https://github.com/rexxars/registry-auth-token) and then update the dependency here. I believe @rexxars will be happy to merge this enhancement if you implement it.

**Comment by leipert** [comment]
@zkochan Even if registry-auth-token extracts the token, it also has to give a token type. So [this line](https://github.com/rstacruz/pnpm/blob/master/lib/got.js#L82) has to read "Basic" instead of "Bearer" if a user uses the config from above
