### ISSUE TITLE
`!` used as delimiter in store conflicts with webpack

### ISSUE THREAD

**Issue by andreypopp** [rstacruz/pnpm#276]
Webpack uses `!` as delimiter between loaders and resources. That means that loading packages from store messes with that. It would be great if pnpm changes `!` to `___` for example. What do you think?

**Comment by rstacruz** [comment]
Oh dear Lord I didn't think of that. I would hope that would be a character
that's not valid in an npm name but valid in a directory name.

**Comment by andreypopp** [comment]
It could be multiple characters, right?

**Comment by alexeyten** [comment]
space? plus? equal-sign? tilde?

**Comment by zkochan** [comment]
Andrey, two underscores can be part of a valid npm package name. That would probably cause similar edge cases to what the exclamation mark caused.

Like Alexey said, the options are: space, +, =, ~
and also: &, $, #, ^, ;, comma

**Comment by zkochan** [comment]
I vote for +

This will be a breaking change. Stores created by previous versions of `pnpm` will not be compatible with the new one. Hence, I suggest to add the pnpm version number to `store.json` and at least print a warning

**Comment by rstacruz** [comment]
Im with @zkochan on his suggestions.
