### ISSUE TITLE
Private github modules not supported

### ISSUE THREAD

**Issue by thalesmello** [rstacruz/pnpm#285]
Whenever I have a private github dependency such as:

```"something": "git+ssh://git@github.com/user/something.git"```

I get the following error:

`Response code 404 (Not Found)`

Notice it's a private repository on Github, which makes ssh authentication
mandatory.

This plugin apparently doesn't work with it.

**Comment by yunasc** [comment]
Can agree. Same issue with git+https:// protocol.

**Comment by zkochan** [comment]
@thalesmello I published ssh support to @zkochan/pnpm

Could you please check if it works for you? If yes, I'll merge and publish to pnpm.

@yunasc private modules can be accessed via https? Where are the tokens taken from?

**Comment by thalesmello** [comment]
@zkochan Worked perfectly! Great implementation, by the way 👍

**Comment by zkochan** [comment]
I've stolen it from ied :-)

Landed in v0.35.0

@yunasc, for the https one lets create a new issue
