### ISSUE TITLE
pnpm prune

### ISSUE THREAD

**Issue by zkochan** [rstacruz/pnpm#299]

**Comment by iamstarkov** [comment]
👍

**Comment by iamstarkov** [comment]
👍

**Comment by iamstarkov** [comment]
this will be hard

**Comment by zkochan** [comment]
I don't think so. This should be easier with pnpm than with npm because we have [strore.json](https://github.com/rstacruz/pnpm/blob/master/docs/store-json.md)

**Comment by zkochan** [comment]
Landed in [v0.37.0](https://github.com/rstacruz/pnpm/releases/tag/v0.37.0)
