### ISSUE TITLE
Question: Does it work with `nvm`?

### ISSUE THREAD

**Issue by lloydwatkin** [rstacruz/pnpm#3]
Will this work with ```nvm```?

Cool project, must train muscle memory to prepend a ***p*** :+1:

**Comment by rstacruz** [comment]
absolutely.

**Comment by colinmollenhour** [comment]
I'd qualify that a bit.. For me when running pnpm via node which was installed via nvm the pnpm command clobbered the node executable in the nvm install:

```
$ pnpm env use --global lts
 WARN  EXDEV: cross-device link not permitted, link '/mnt/c/Users/Colin/.pnpm-store/v3/files/files/79/e3a117b3fb152e413382ee40e3aa91fab80beee7d8a400656a3072f19915ec1a8900fc3d17c9751e7769dc1cde5a71b3a8d62f0182f7b5f0b98888e3c643b2-exec' -> '/home/colin/.local/share/pnpm/nodejs/_tmp_27719_97048f4f340835574ed2ac62f91111ff/bin/node'
Falling back to copying packages from store
Node.js 16.13.1 is activated
  /home/colin/.nvm/versions/node/v17.0.1/bin/node -> /home/colin/.local/share/pnpm/nodejs/16.13.1/bin/node
```

Also I am using WSL but not sure how it was aware of my native windows Node installation..

**Comment by LemuelKL** [comment]
> I'd qualify that a bit.. For me when running pnpm via node which was installed via nvm the pnpm command clobbered the node executable in the nvm install:
> 
> ```
> $ pnpm env use --global lts
>  WARN  EXDEV: cross-device link not permitted, link '/mnt/c/Users/Colin/.pnpm-store/v3/files/files/79/e3a117b3fb152e413382ee40e3aa91fab80beee7d8a400656a3072f19915ec1a8900fc3d17c9751e7769dc1cde5a71b3a8d62f0182f7b5f0b98888e3c643b2-exec' -> '/home/colin/.local/share/pnpm/nodejs/_tmp_27719_97048f4f340835574ed2ac62f91111ff/bin/node'
> Falling back to copying packages from store
> Node.js 16.13.1 is activated
>   /home/colin/.nvm/versions/node/v17.0.1/bin/node -> /home/colin/.local/share/pnpm/nodejs/16.13.1/bin/node
> ```
> 
> Also I am using WSL but not sure how it was aware of my native windows Node installation..

WSL adds Windows path elements to the $PATH environment variable. You can disable this behaviour by confirguring the `wsl.conf`, see [https://docs.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings](url).

**Comment by Giszmo** [comment]
I ended up with my `$PATH` being prepended with `~/.local/share/pnpm:` which broke my `mvn`.
