### ISSUE TITLE
Retry when fetch from npm registry fails

### ISSUE THREAD

**Issue by zkochan** [rstacruz/pnpm#317]
Sometimes the pnpm tests fail with errors like this

```
    ✖ RequestError
    ---------------
      operator: error
      expected: |-
        undefined
      actual: |-
        { code: 'ECONNRESET', host: 'registry.npmjs.org', hostname: 'registry.npmjs.org', message: undefined, method: 'GET', path: '/rimraf/-/rimraf-2.5.4.tgz' }
      stack: |-
```

npm by default retries to fetch the packages once more. And this logic is configurable via the [fetch-retries](https://docs.npmjs.com/misc/config#fetch-retries) config.

pnpm can use the same config value and pass it to got, [which already supports retries](https://www.npmjs.com/package/got#retries).

**Comment by zkochan** [comment]
Implementing [Benchmark suite](https://github.com/rstacruz/pnpm/issues/56) might help with covering this with unit tests. I think.

**Comment by KostyaEsmukov** [comment]
+1 on this.

Experiencing failures due to random 500s (it's `--quiet` mode):

    Response code 500 (Internal Server Error)
    GET registry.npmjs.org/@angular%2Fcommon

**Comment by zkochan** [comment]
Actually got retries 5 times by default

Probably we have to use [retry](https://www.npmjs.com/package/retry) which is used by npm and support the set of configs that is passed to it: fetch-retries, fetch-retry-factor, fetch-retry-mintimeout, fetch-retry-maxtimeout

**Comment by zkochan** [comment]
I think this package can be used instead of got - [got-retry](https://github.com/vdemedes/got-retry)

It combines got with retry. Exactly what we need
