### ISSUE TITLE
Switching to AVA from tape?

### ISSUE THREAD

**Issue by zkochan** [rstacruz/pnpm#323]
I've started to work on [Benchmark suite](https://github.com/rstacruz/pnpm/issues/56) and realized there's a need in some `before` functionality. Tape doesn't have a built-in `before` function. Although it is possible to make a "setup" test, that would make it impossible to use the `test.only` functionality, which is pretty convenient when working on new features.

On the other hand, AVA seems to have everything that tape has + [Before & after hooks](https://github.com/avajs/ava#before--after-hooks)

**Comment by andreypopp** [comment]
ava from my limited experience with it:
- cons: poor string diff, almost totally unreadable
- cons: slow startup (parallel election pays off only for really large test suites)

**Comment by zkochan** [comment]
Well poor diffing can be fixed by using some other TAP reporter instead of the default one.

About the slow startup you might be right. However, with AVA it is also possible to run tests inside one file concurrently. That might give a boost to the performance, but we'll have to rewrite our tests. Currently they'll work only when executed serially.

Disclaimer. I've never actually used AVA before. All I know about it is from its documentation.

**Comment by jamen** [comment]
Agreed with @andreypopp on the second point.  For the results I use `tap-spec` with `ava -t`.

**Comment by zkochan** [comment]
It also can't run with `--preserve-symlinks` and pnpm currently uses that option when installing binstabs, so I'll just close this issue now :-)
