### ISSUE TITLE
Looks like some modules are not installed

### ISSUE THREAD

**Issue by Grawl** [rstacruz/pnpm#337]
### pnpm version:

```
$ pnpm -v
0.29.0
```

### Code to reproduce the issue:

```
$ pnpm i
$ gulp
```

### Expected behavior:

With regular `npm i` my gulp build is passed.

### Actual behavior:

gulp build is errored because of `imagemin-jpegtran` from `gulp-imagemin` is not found

### Additional information:

 - `node -v` prints: `v6.2.2`
 - OS X

`$ gulp` output, `gulpfile.js`, `package.json`, `$ pnpm i` output: https://gist.github.com/Grawl/cd46b291fd05591e110377ca76494619

**Comment by iamstarkov** [comment]
`jpegtran-bin` is fine, though [smth wrong with `archive-type`](https://gist.github.com/Grawl/cd46b291fd05591e110377ca76494619#file-pnpm-i-L200-L210)

**Comment by iamstarkov** [comment]
and [smth wrong with `globby`](https://gist.github.com/Grawl/cd46b291fd05591e110377ca76494619#file-pnpm-i-L211)

>      globby ^5.0.0 ERROR ✗ /wp-content/themes/crossbar/node_modules/.tmp/1472653081896_bin-build@^2.0.0/_/index.js:3:19)

**Comment by iamstarkov** [comment]
though i cant see, how you gulp build is runned after npm install

**Comment by iamstarkov** [comment]
do you have this project as oss project on github?

**Comment by Grawl** [comment]
no, I can't share this project. it's not open source. we develop this on own git server.

**Comment by iamstarkov** [comment]
it will be hard to actually reproduce your gulp build failure

**Comment by iamstarkov** [comment]
at least i will try to reproduce missing packages here https://github.com/iamstarkov/pnpm-issue-337

**Comment by Grawl** [comment]
I think we can try to use any gulp generator from Yeoman, like yeogurt, and have the same problems: https://gist.github.com/Grawl/4404df96380856a106fc70787d3e1a6f

**Comment by iamstarkov** [comment]
found failing dep:
```
  "devDependencies": {
    "gulp-imagemin": "^3.0.1"
  }
```

**Comment by iamstarkov** [comment]
1. everytime fail begins with problems on `postinstall` step
2. issue is not permanent, its kind of floating around binaries being not able to compiled

**Comment by iamstarkov** [comment]
though, [all failing deps are optional](https://github.com/sindresorhus/gulp-imagemin/blob/master/package.json#L52-L57), so pnpm is fine with them not being compiled

**Comment by iamstarkov** [comment]
i was not able to pipe `pnpm install log to the file` =(

**Comment by iamstarkov** [comment]
@andreypopp @zkochan @rstacruz feel free to investigate further from here
```
git clone https://github.com/iamstarkov/pnpm-issue-337
cd pnpm-issue-337
pnpm i
```

**Comment by Grawl** [comment]
@iamstarkov 

> i was not able to pipe `pnpm install` log to the file =(

I've just copied it right from Terminal with my mouse 😉

**Comment by zkochan** [comment]
I suggest to continue investigating this once we merge and publish [Create pnpm-debug.log file on fail](https://github.com/rstacruz/pnpm/pull/343)

**Comment by zkochan** [comment]
Here's the debug info: https://gist.githubusercontent.com/zkochan/e42a33e54192b38d9184575c5d1e4aee/raw/8870d135902473eb4fd1dcbfe8b3dfce83e2691e/ppm-debug.yaml

Seems like `archive-type` is not installed yet, when the postinstall script is being executed.

I also noticed that npm doesn't have this errors and it runs postinstalls after all the deps are downloaded... pnpm seems to be more greedy, it runs postinstall as soon as possible.

**Comment by zkochan** [comment]
Indeed, after moving the postinstall scripts execution after installation, the package created by @iamstarkov always installs with no issues. You can try the fix on branch issue337. (NOTE: my fast dirty fix has broken the skipping of optional dependencies, but that'll be easy to fix, if this is really the solution)

**Comment by zkochan** [comment]
@Grawl I have published what I think is the fix to `@zkochan/pnpm`

Please install it and try it on your project.

`npm i -g @zkochan/pnpm`

**Comment by Grawl** [comment]
@zkochan looks like it fixed now. all modules are installed without errors, gulp works fine.
