### ISSUE TITLE
Bundling pnpm dependencies

### ISSUE THREAD

**Issue by zkochan** [rstacruz/pnpm#338]
The idea is to make pnpm installation super fast. If pnpm installation is fast enough, we can recommend to use it instead of npm on travis/appveyor installations. pnpm installation won't increase significantly the setup time but will decrease significantly the installation time of the dependencies.

To make pnpm installation fast, all its dependencies have to be bundled with the package.

Possible solutions:

1. using the `bundledDependencies` feature of npm. See branch [bundled-deps-2](https://github.com/rstacruz/pnpm/tree/bundled-deps-2)
2. using some hacks that will allow to publish the content of the `node_modules` with pnpm. Working implementation: https://github.com/rstacruz/pnpm/pull/310
3. using a bundler like rollup.

TODO: add Pros and Cons of each solution

**Comment by iamstarkov** [comment]
Is there 3rd option? we probably can use bundler like rollup to achieve that

**Comment by zkochan** [comment]
Seems like bower is doing this as well. I will look into how they do it
