### ISSUE TITLE
Add collaborative etiquette to contributing.md

### ISSUE THREAD

**Issue by rstacruz** [rstacruz/pnpm#342]
> This project follows [collaborative etiquette](http://git.io/col) guidelines.

Curious, what do you all think?

**Comment by zkochan** [comment]
I like that etiquette. I think the reference can be in the first paragraph of CONTRIBUTING.md:

## Collaborative Etiquette

[![](https://img.shields.io/badge/%E2%9C%93-collaborative_etiquette-brightgreen.svg)](https://git.io/col)

This project follows [collaborative etiquette](http://git.io/col) guidelines.

**Comment by iamstarkov** [comment]
I think its good idea
