### ISSUE TITLE
Using static typing

### ISSUE THREAD

**Issue by zkochan** [rstacruz/pnpm#347]
I think rewriting pnpm to TypeScript would be beneficial.

1. I remember several bugs that TypeScript would have caught automatically. For instance, this one: 84d9aa508dcd40d1a396402f68e55c29cb72a8d8.
2. From a marketing perspective this would be another plus over npm/ied.
3. For the community it would be easier to contribute to pnpm with type checking, auto-completion, hints and other awesome stuff the TypeScript provides.

**Comment by iamstarkov** [comment]
Does pnpm have programmatic API to use?

**Comment by zkochan** [comment]
yes, https://github.com/rstacruz/pnpm/blob/master/docs/api.md

**Comment by iamstarkov** [comment]
than, typescript will not help raw-js consumers to validate their code anyway. and there is not run-time check as far as i know it

**Comment by iamstarkov** [comment]
also, a lot of people will complain about implementing it in flow instead

**Comment by zkochan** [comment]
I am not really familiar with flow, but I was under the impression that it has the same syntax as TypeScript but better tooling.

It will not change anything for the raw-js users but it would make the life of pnpm maintainers easier.

**Comment by zkochan** [comment]
We can even look at it as a smarter eslint... For instance, like a month ago I changed a method called `linkBins` to accept only 1 argument. And only recently I noticed that in 1 place I did not update the code which was using it 7ffb692b24650b4da9a2d78258351306c0dc710b. It wasn't a bug, because the additional args were just ignored, but the code looked weird. TypeScript would've caught that

**Comment by andreypopp** [comment]
I'm all for static typing, but I'd rather go with Flow as it has more powerful type system and thus much better chances to catch an error.

As a con for both TypeScript and Flow is that build process becomes necessary: you can't run code before transpiring it (well, you can with `flow-node` for example and I think something like this exists for TypeScript).

I could make a PR with such build process incorporated and some of the modules annotated with Flow to see how it feels.

**Comment by iamstarkov** [comment]
> make the life of pnpm maintainers easier

thats a good point

**Comment by iamstarkov** [comment]
I will be able to read and edit static-typed js as well, i guess.

So @zkochan, @andreypopp pick a side and go ahead =)

**Comment by zkochan** [comment]
Well, personally I like TypeScript 2 more, but it is in beta yet and it is easier to convert an existing project to Flow. So if @andreypopp wants Flow, I don't resist.

And we can switch to TypeScript later, in case it will become superior.
