### ISSUE TITLE
bin stubs not created for a certain repo

### ISSUE THREAD

**Issue by mourner** [rstacruz/pnpm#351]
### Code to reproduce the issue:

```
git clone http://github.com/mapbox/mapbox-gl-js
cd mapbox-gl-js
pnpm install
ls node_modules/.bin
```

### Expected behavior:

A list of bin stubs from dependencies/devDependencies.

### Actual behavior:

```
ls: node_modules/.bin: No such file or directory
```

It works fine in other repos I tested, but for some reason fails for this one. On a CI server (Circle), it's even stranger — some stubs are created and some others (like `eslint`) are not.

### Additional information:

 - `node -v` prints: v6.5.0
 - OS X El Capitan

cc @rstacruz

**Comment by iamstarkov** [comment]
can verify it

**Comment by iamstarkov** [comment]
can verify it

**Comment by iamstarkov** [comment]
related #96 and reasoning in #58

**Comment by iamstarkov** [comment]
not sure what to do

**Comment by mourner** [comment]
@iamstarkov yeah, the difference here is that it doesn't create bin stubs for direct dependencies (not deep ones).

**Comment by zkochan** [comment]
I have noticed this issue as well today. I think there is an uncatched promise error during installation... I am looking into it now

**Comment by zkochan** [comment]
no, I don't see not catched promise errors. Seems like it was broken in v0.31.0. v0.30.0 creates the binstubs

**Comment by zkochan** [comment]
this commit caused the issue https://github.com/rstacruz/pnpm/commit/1c92146e424164afdec57f9d483ebe69470fcf90

**Comment by iamstarkov** [comment]
@zkochan but why? `linkBins` just moved from one place to another

**Comment by zkochan** [comment]
I really don't know, but when I revert that commit, it works...

**Comment by zkochan** [comment]
When I return that line, it works https://github.com/rstacruz/pnpm/commit/1c92146e424164afdec57f9d483ebe69470fcf90#diff-f6618e1cc731d58106a806b7679a7616L106

**Comment by zkochan** [comment]
I've found the issue.... Not in the commit I was thinking... reverting that commit was just fixing one of the issues caused by tarball dependencies not working. The fix is easy, I think I will create a PR soon

**Comment by zkochan** [comment]
Fixed in [v0.31.2](https://github.com/rstacruz/pnpm/releases/tag/v0.31.2)

**Comment by mourner** [comment]
@zkochan thank you very much for such a quick fix!

**Comment by zkochan** [comment]
нема за що :-)
you're welcome
