### ISSUE TITLE
Use npm-registry-client instead of got+retry

### ISSUE THREAD

**Issue by zkochan** [rstacruz/pnpm#367]
`npm` uses [npm-registry-client](https://github.com/npm/npm-registry-client) for making requests to the registry and downloading tarballs. `pnpm` can use it as well.

**Comment by iamstarkov** [comment]
what are the pros/cons?

**Comment by zkochan** [comment]
I just see that we have sometimes errors like this [getaddrinfo ENOTFOUND registry.npmjs.org](https://github.com/rstacruz/pnpm/issues/87). npm seems to not have it. Maybe there is something in `npm-registry-client` that we don't have? Currently I see the difference only in the user agent that we use. We send `pnpm` and `npm-registry-client` sends `node/<version>`

**Comment by iamstarkov** [comment]
Let's try

**Comment by zkochan** [comment]
Landed in [v0.36.0](https://github.com/rstacruz/pnpm/releases/tag/v0.36.0)
