### ISSUE TITLE
The strict-ssl config is ignored

### ISSUE THREAD

**Issue by carmelone** [rstacruz/pnpm#373]
### Expected behavior:

Everything good.

### Actual behavior:

"strict-ssl=false" in .npmrc or /users/.npmrc ignored at all and "Unable to verify certificate error".

**Comment by zkochan** [comment]
This should be easy to fix. We use [npm-registry-client](https://www.npmjs.com/package/npm-registry-client). We just need to set the `ssl.strict` option for it

**Comment by carmelone** [comment]
Where can I start?

**Comment by zkochan** [comment]
The RegClient is created [here](https://github.com/rstacruz/pnpm/blob/master/src/network/got.ts#L36). You just have to pass the option there. The option should be added also to [PublicInstallationOptions](https://github.com/rstacruz/pnpm/blob/master/src/api/install.ts#L46) as `sslStrict` and to all the places where TypeScript will tell you

**Comment by zkochan** [comment]
I suggest to set not just ssl.strict but all the other options that npm passes to npm-registry-client as well. [Here's a map of npm configs to npm-registry-client options](https://github.com/npm/npm/blob/9e03561547ec5830c5f61caa4e6221d4d3b813aa/lib/cache/caching-client.js#L196-L218)

**Comment by zkochan** [comment]
Landed in [v0.37.0](https://github.com/rstacruz/pnpm/releases/tag/v0.37.0)
