### ISSUE TITLE
Using private registry (ex sinopia) after login and whoami I got: "unregistered users are not allowed to access package"

### ISSUE THREAD

**Issue by carmelone** [rstacruz/pnpm#376]
### Actual behavior:

I'm using sinopia (latest version), with npm everything ok, I can access repo and download everything. Instead, with pnpm I can `pnpm login` (.npmrc in "Users/user" is created as I'm using npm), `pnpm whoami` works good and tells me who am I. But when I try `pnpm i` I got this:

`unregistered users are not allowed to access package`.

If I try the `get` call of pnpm with (ex.) Postman everything is ok, with the same body (Bearer token and all). Why this?

### Additional information:

 - `node -v` prints: 6.6.0
- `npm -v` prints: 3.10.6
 - Windows

**Comment by zkochan** [comment]
I've setup sinopia locally, published some packages there and tried to install them. Everything worked. I tried a normal package and a scoped one. Also I tried to install packages from npm and it worked. Could you localize on what package type the error happens?

Is it a semver dependency, a scoped dep? Is it hosted on your local sinopia or on npm?

**Comment by zkochan** [comment]
And why does it need authorization for installing from sinopia? I thought sinopia requires authorization only for publishing

**Comment by zkochan** [comment]
@carmelone this is fixed in the latest pnpm. The fix landed in [v0.41.2](https://github.com/rstacruz/pnpm/releases/tag/v0.41.2)
