### ISSUE TITLE
Configure from API

### ISSUE THREAD

**Issue by connorhartley** [rstacruz/pnpm#383]
Is it possible to set configuration variables from the API? If not, I would like to suggest that.

**Comment by zkochan** [comment]
Do you mean these commands - [npm config](https://docs.npmjs.com/cli/config)?

They will pass through to npm. pnpm uses and sets the same configs that npm would

If you mean whether the programmatic API has a function for setting the configs then - no

**Comment by connorhartley** [comment]
Should be able to set the configs at the beginning of a command using the flags `--userconfig` and `--globalconfig` so this is fine. Thanks.
