### ISSUE TITLE
Optional dependencies

### ISSUE THREAD

**Issue by rstacruz** [rstacruz/pnpm#39]
They should be installed when possible.

**Comment by patrickheeney** [comment]
What is needed for this?

I am not sure if this [right spot](https://github.com/rstacruz/pnpm/blob/master/lib/install.js#L207), could be as simple as:

```
    // recurse down to dependencies
    .then(_ => log('optional dependencies'))
    .then(_ => installAll(ctx,
      fulldata.optionalDependencies,
      join(paths.tmp, '_', 'node_modules'),
      { keypath: pkg.keypath.concat([ pkg.fullname ]) }))
```

**Comment by iamstarkov** [comment]
i would like to get it as well, `ava --watch` is not running out of the box, so i have to install [optional `chokidar` everytime](https://github.com/rstacruz/markdown-it-named-headings/pull/1/commits/b8d9444dd06f8f003a31323bcda363108a546845)

**Comment by patrickheeney** [comment]
@rstacruz Can you chime in here? Will the code above work?

**Comment by zkochan** [comment]
I'll try to implement it this weekend

**Comment by andreypopp** [comment]
That would be rad. I constantly forget to install fsevents and my battery drains fast.
