### ISSUE TITLE
`pnpm i $dep` should not trigger prepublish hook

### ISSUE THREAD

**Issue by julien-f** [rstacruz/pnpm#396]
`NPM-SCRIPTS(7)`:
> prepublish: Run BEFORE the package is published.  (Also run on **local npm install without any arguments**.)

### Code to reproduce the issue:

`package.json`:

```json
{
  "scripts": {
    "prepublish": "echo prepublish"
  }
}
```

### Expected behavior:

```
$ pnpm i lodash
  lodash                                                           4.16.3 ✓
```

### Actual behavior:

```
$ pnpm i lodash
  lodash                                                           4.16.3 ✓ 

> @ prepublish /tmp/tmp.O6KYLvqC8R/tmp/issue-pnpm-hooks
> echo prepublish

prepublish
```

### Additional information:

 - `node -v` prints: v6.4.0
 - Windows, OS X, or Linux?: Linux

**Comment by iamstarkov** [comment]
I believe actual behavior is correct, and the same as npm has. https://github.com/npm/npm/issues/10074

**Comment by julien-f** [comment]
No it's not, `npm` runs `prepublish` on `npm install` only when there are no arguments (no deps).

**Comment by iamstarkov** [comment]
@julien-f you are right, i was wrong

**Comment by julien-f** [comment]
No problem, thanks for your input :)
