### ISSUE TITLE
Possibly helpful?

### ISSUE THREAD

**Issue by DTrejo** [rstacruz/pnpm#4]
Great work with this!

I don't know if it will help you in any way, but if you see any code in https://github.com/dtrejo/urn that you'd like to "steal" / re-use, please feel free. It does "cp -R" to install packages from `~/.npm` when there is no internet.

Cheers and keep up the good work!
David

Note: just looked at the code; probably nothing you'll want to use. Thanks for pnpm!

**Comment by rstacruz** [comment]
thanks for the heads up!

**Comment by DTrejo** [comment]
pnpm, downloading from the network (and maybe also pulling from npm cache?) is fasting than urn, doing "cp r". Awesome :) Closing this cause you have better things to do! pnpm doesn't yet work offline, but if I am ever on an airplane, programming, and get annoyed at slow installs, expect a PR :)

**Comment by rstacruz** [comment]
actually i'm hoping to get a global `.store` at some point :) it will answer that concern too
