### ISSUE TITLE
pnpm does not transfer return code from underlying command

### ISSUE THREAD

**Issue by viliusl** [rstacruz/pnpm#402]
### pnpm version: 
0.39.0

### Code to reproduce the issue:
 - create a blank repo (npm init);

### Expected behavior:
 - run `pnpm install && pnpm test && echo "Should not be printed"`;

 - output:
```
$ pnpm install && pnpm test && echo "Should not be printed"

> pnpm-code@1.0.0 test /Users/viliusl/Projects/support/pnpm-code
> echo "Error: no test specified" && exit 1

Error: no test specified
npm ERR! Test failed.  See above for more details.
```

Command sequence terminated and "Should not be printed" not printed as pnpm test exited with code 1.

### Actual behavior:
 - run `pnpm install && pnpm test && echo "Should not be printed"`;

 - output:
```
$ pnpm install && pnpm test && echo "Should not be printed"

> pnpm-code@1.0.0 test /Users/viliusl/Projects/support/pnpm-code
> echo "Error: no test specified" && exit 1

Error: no test specified
npm ERR! Test failed.  See above for more details.
Should not be printed
```

"Should not be printed" was actually printed.

### Additional information:
 - `node -v` prints: v6.7.0
 - Windows, OS X, or Linux?: OS X 10.11.6

**Comment by zkochan** [comment]
If someone would like to fix this. Here is where the fix should be https://github.com/rstacruz/pnpm/blob/master/src/bin/pnpm.ts#L86-L89

And a new unit test. Probably a new unit test file can be created called cli.ts
