### ISSUE TITLE
npm-run-all does not work with pnpm on Node 6

### ISSUE THREAD

**Issue by zkochan** [rstacruz/pnpm#413]
### Code to reproduce the issue:

pnpm i npm-run-all

write a script using npm-run-all

run the created script
### Expected behavior:

npm-run-all works in scripts
### Actual behavior:

npm-run-all does not work
### Additional information:
- `node -v` prints:
- Windows, OS X, or Linux?: Linux

**Comment by zkochan** [comment]
A workaround is to run the command from the package: `node node_modules/npm-run-all/bin/npm-run-all`

**Comment by iamstarkov** [comment]
have this issue with projects at work, was not sure if it have anything to do with pnpm

**Comment by zkochan** [comment]
it is nothing critical but it is because of a difference that pnpm has.

I checked the source code of npm-run-all. They check if the entry point of the command was bin/npm-run-all/index.js. pnpm creates a proxy file to preserve symlinks, so it is not the entry point..

**Comment by iamstarkov** [comment]
can we fix that in pnpm, or can we suggest pr to npm-run-all?

**Comment by iamstarkov** [comment]
this package is somewhat important for decent cross-platform dx for packages with complicated npm scripts

**Comment by zkochan** [comment]
Maybe we could use an sh file instead of a proxy js file.

**Comment by zkochan** [comment]
This has been fixed on `npm-run-all` side.

**Comment by iamstarkov** [comment]
awesome
