### ISSUE TITLE
Create a website that compares Node package managers speed

### ISSUE THREAD

**Issue by zkochan** [rstacruz/pnpm#422]
Now that we have a serious competitor it would be nice to visualize in what areas are we better/worse than other package managers.

I was thinking about both a tool that would run the same commands on npm/yarn/pnpm and a static website that would show tables/diagrams of how fast are the same actions on different tools.

**Comment by iamstarkov** [comment]
what are the metrics?

**Comment by iamstarkov** [comment]
im sure there is pure node js analogue to unix `time` (`$ time npm i`), travis supports cron jobs. so we good to go

**Comment by zkochan** [comment]
Something like [this](https://github.com/zkochan/dependency-managers-benchmark)

First results were
```
npm install babel-cli --force --ignore-scripts: 40597.818ms
yarn add babel-cli --force --ignore-scripts: 7737.555ms
pnpm install babel-cli --force --ignore-scripts: 6809.358ms
```

**Comment by zkochan** [comment]
Only one test for now, the results are automatically written to the readme in this project: [dependency-managers-benchmark](https://github.com/zkochan/dependency-managers-benchmark). Measuring speed and disk usage.

**Comment by zkochan** [comment]
I want to do speed comparison for react/angular/ember apps. The results are amazing! For a react app pnpm is more than 6 times faster than yarn and uses 20 times less disc scpace!

| command | time in ms | size in bytes |
| --- | --- | --- |
| npm install | 69026 | 96825002 |
| yarn | 33270 | 178080338 |
| pnpm install | 5382 | 8727354 |

**Comment by zkochan** [comment]
Seems like pnpm is pretty good compared even to yarn!

It installs the dependencies of a react-app 4 times faster

| command | time in ms | size in bytes |
| --- | --- | --- |
| npm install | 65479 | 96825002 |
| yarn | 32558 | 175712562 |
| pnpm install | 8324 | 91086578 |

I'll add more fixtures for comparison. Probably an angular app, ember app, an express app, a hapi app.
