### ISSUE TITLE
Does not work with private package hosted in GemFury

### ISSUE THREAD

**Issue by misterbyrne** [rstacruz/pnpm#44]
We use GemFury to host private npm packages. It handles requests for private packages itself and proxies the rest to the npm registry. So the semver style URLs work for public packages, but not for private ones (since GemFury doesn't support them and 404s).

https://gemfury.com/help/npm-registry

**Comment by rstacruz** [comment]
okay, i know why this might be, we're using the not-so-documented `https://registry.npmjs.org/lodash/>=4.0.0` endpoint when we should be using `https://registry.npmjs.org/lodash`.

**Comment by rykov** [comment]
Michael from Gemfury here.  Can you talk a bit about how this would work if we support it on our end?  Are you sending the version range verbatim from `package.json`'s dependencies map such that we need to support all cases here: https://docs.npmjs.com/files/package.json#dependencies?

**Comment by rstacruz** [comment]
hey there! 

> Are you sending the version range verbatim from package.json

Yes, they're being sent out as either semver `version`s (like *4.0.0*), `range`s (like *^4.0.0*, or even *> 4.0.0 < 4.1.0*), or `dist-tag`s (like *latest*). They're expected to be handled by npm [semver](https://www.npmjs.com/package/semver).

**Comment by misterbyrne** [comment]
Closing since this is working now
