### ISSUE TITLE
Fetching sub-dependencies sooner

### ISSUE THREAD

**Issue by zkochan** [rstacruz/pnpm#453]
Currently pnpm downloads a package from the npm registry, unpacks it and uses the `package.json` from the unpacked directory to identify what sub-dependencies should be installed.

However, the package.json is available sooner! The registry sends all the package.json's, when the package meta information is requested!

So pnpm can start to download all the subdependencies a lot sooner!

**Comment by iamstarkov** [comment]
awesome news

**Comment by zkochan** [comment]
So far it improved performance only by ~3.5%. I will try to make it faster. Maybe I am missing something.
