### ISSUE TITLE
Override the node command when using pnpm run

### ISSUE THREAD

**Issue by zkochan** [rstacruz/pnpm#463]
Frequently there are actions made with node in scripts. When dependencies are installed with pnpm, it is recommended to run node with the --preserve-symlinks option.

The easiest solution might be to override the run command in pnpm. The pnpm version of the run command would run all the node commands in scripts with the --preserve-symlinks option

**Comment by iamstarkov** [comment]
seems fragile

**Comment by iamstarkov** [comment]
but the only way, i think

**Comment by zkochan** [comment]
There will be a better solution once this gets released: https://github.com/nodejs/node/issues/8509 (Configuration option to permanently turn on --preserve-symlinks)

**Comment by iamstarkov** [comment]
so it will be in next node release?

**Comment by zkochan** [comment]
in the 7th for sure. The 6th is under question for now.

**Comment by iamstarkov** [comment]
6 is LTS now, so i doubt it

**Comment by zkochan** [comment]
[Here](https://github.com/nodejs/node/pull/8749#issuecomment-255844459) they say they will discuss it. If they decide not to include it, we can implement the hack solution for v6

**Comment by zkochan** [comment]
I think we don't need `--preserve-symlinks` anymore. As of v0.47.0, Node.js 4 should work fine without preserve-symlinks. It is used on Node 6 and newer but can be turned off via the `preserve-symlinks` config.
