### ISSUE TITLE
Directories in store cannot contain colons

### ISSUE THREAD

**Issue by zkochan** [rstacruz/pnpm#479]
### pnpm version:

0.45.0

### Code to reproduce the issue:

pnpm i git+ssh://git@github.com/kevva/is-negative.git

### Expected behavior:

Successful installation

### Actual behavior:

There is an error when creating a folder in the store for the git-hosted package. The reason for that is because the folder name cannot contain a colon.

### Additional information:

 - `node -v` prints: 7.1.0
 - Windows, OS X, or Linux?: Windows

**Comment by iamstarkov** [comment]
oh gosh
