### ISSUE TITLE
Storage layout incompatible with Ember dependency checker

### ISSUE THREAD

**Issue by misterbyrne** [rstacruz/pnpm#49]
Ember CLI has a dependency checker which ensures you have the required npm modules installed.

https://github.com/quaertym/ember-cli-dependency-checker

This can currently we worked around by setting an environment variable, e.g.

`SKIP_DEPENDENCY_CHECKER=true ember server`

Will possibly be fixed by https://github.com/rstacruz/pnpm/pull/46

**Comment by rstacruz** [comment]
try it now... v0.13.0 is out. be sure to `rm -rf node_modules/` first so you get the new updates.

**Comment by misterbyrne** [comment]
Great stuff! No complaints from Ember now! :raised_hands:
