### ISSUE TITLE
support inherited dependencies ("peerDependencies")

### ISSUE THREAD

**Issue by jkroso** [rstacruz/pnpm#5]
packages like `pg-then` will `require('pg')` even though they don't declare it as a dependency. This works with npm since `pg-then` ends up being installed in the same node_modules folder as `pg` but when they are symlinked from a global store this doesn't work. And `babel-runtime` does `require('babel-runtime')`. haha

These packages should declare these dependencies in "peerDependencies" but they don't because with npm they can get away without it.

And BTW the hackery I mentioned in #1 won't be necessary if `pnpm` support "peerDependencies" and if packages use it correctly

**Comment by rstacruz** [comment]
> And babel-runtime does require('babel-runtime'). haha

This is accounted for, actually. `babel-runtime@5.8.12/node_modules/babel-runtime` is a symlink to `babel-runtime@5.8.12`. I don't know why they'd bother doing that though, it seems only `babel-runtime@^5` has this issue... but yeah, I'm able to get babel to work with pnpm here.

> These packages should declare these dependencies in "peerDependencies" but they don't because with npm they can get away without it.

peerDependencies isn't "supported" by npm, btw. Modern npm2 and npm3 versions won't install any peerDependencies for you. With `pg-then` + `pg`, you're expected to add both to your project. This is the same with other similar setups (some of these examples declare others as peerDependencies, some don't):

* `eslint` + `eslint-config-standard`
* `jsdom` + `jsdom-global`
* `pg` + `knex`
* `babel-preset-es2015` + `babel-runtime` (or `babel-register`, `babelify`, `babel-core`)
* `browserify` + `babelify`
* etc...

pnpm more or less mirrors `npm@2`'s behavior.
