### ISSUE TITLE
Post-install script is not being executed

### ISSUE THREAD

**Issue by misterbyrne** [rstacruz/pnpm#50]
When the `package.json` in the current directory contains a `postinstall` script `pnpm` does not run it, but `npm` does.

**Comment by rstacruz** [comment]
Ohhh. Forgot that one. Nice catch.

**Comment by zkochan** [comment]
prepublish should be executed as well.

from the npm site

> prepublish: Run BEFORE the package is published. (Also run on local npm install without any arguments.)

<https://docs.npmjs.com/misc/scripts>

I need this feature now, so I'll probably work on a pull request today
