### ISSUE TITLE
Can't install different version once installed

### ISSUE THREAD

**Issue by misterbyrne** [rstacruz/pnpm#51]
In a new directory enter `pnpm install ember-cli@1.13.13`
When it's finished, enter `pnpm install ember-cli@1.13.15`

Nothing happens - the previous version remains.

**Comment by rstacruz** [comment]
Yeah, it doesn't verify installed versions, haha. Not yet anyway. Something
to fix before declaring 1.0.0 for sure.

As a workaround, "rm" the symlink in node_modules/ember-cli first.

**Comment by rstacruz** [comment]
thanks for the reports, btw! feedback at this point really helps in prioritizing what's important to folks and finding edge cases i may not be finding myself.

**Comment by misterbyrne** [comment]
No probs - I'm very excited about this project! 😄 Awesome work!

**Comment by zkochan** [comment]
This one was fixed
