### ISSUE TITLE
EEXIST: file already exists, link

### ISSUE THREAD

**Issue by Akkuma** [rstacruz/pnpm#531]
### pnpm version: 
v0.46.0 & v0.47.0

### Code to reproduce the issue: 
`pnpm i`

[pnpm-debug.log.zip](https://github.com/rstacruz/pnpm/files/697078/pnpm-debug.log.zip)

### Expected behavior: 
Successfully installs

### Actual behavior: 
Throws an error

### Additional information:

 - `node -v` prints: v7.4.0 also fails under v4.4.5
 - Windows, OS X, or Linux?: OS X

**Comment by zkochan** [comment]
Thanks for reporting, I'll try to fix it ASAP

**Comment by zkochan** [comment]
Fix landed in [v0.47.1](https://github.com/rstacruz/pnpm/releases/tag/v0.47.1)
