### ISSUE TITLE
How to write about disk usage advantages of pnpm in the docs?

### ISSUE THREAD

**Issue by zkochan** [rstacruz/pnpm#539]
Currently the package description of pnpm is `Performant npm installations` and nowhere in the docs is a word about the disk space saving that pnpm achieves with machine store.

I wonder what would be the shortest wording to put it maybe even to the description.

Maybe: `Fast, disk space efficient npm installs`

Is it a good description to describe pnpm's biggest advantages?

**Comment by iamstarkov** [comment]
shall we add npm compatible?

**Comment by zkochan** [comment]
I think `npm installs` already note that. Or what do you mean?

**Comment by iamstarkov** [comment]
u r right

**Comment by andreypopp** [comment]
OT: If we get plugin API in we could say that pnpm is about *programmatic* npm installs also. :-)
