### ISSUE TITLE
Package fetches are not transactional

### ISSUE THREAD

**Issue by andreypopp** [rstacruz/pnpm#547]
Sorry for no repro for this issue, I'm filing it just not to forget to submit a PR which fixes it.

Package fetches are not transactional — that means if an other package's installation fails during the fetch/unpacking, then the store is left in inconsistent state — the dir exists and thus pnpm thinks it's ready.

**Comment by zkochan** [comment]
This is a regression. The way this issue was solved in the past, packages were refetched to the store if they were not in store.yaml. There is even a test for that, but seems like the tests stopped working correctly after the big rewrite

**Comment by zkochan** [comment]
But I think your solution is better because on an installation failure, part of the packages might be fetched correctly. With my solution all the packages would be considered invalide
