### ISSUE TITLE
Benchmark suite

### ISSUE THREAD

**Issue by davej** [rstacruz/pnpm#56]
I would be up for working on this.

My thinking is that I will mock the network endpoints (registry mocker here: https://github.com/npm/npm-registry-mock) so that it's not network dependent. Could also be integrated with Travis, although I'm guessing that the performance might differ greatly based upon the VM you get assigned when the build is run.

@rstacruz: Do you have any thoughts?

**Comment by rstacruz** [comment]
yes, we definitely need a way to do isolated unit tests (rather than the "real-world" integration tests we have now)!

**Comment by rstacruz** [comment]
>  I'm guessing that the performance might differ greatly based upon the VM 

I'm sure of that too, but having a benchmarking suite is a good step forward nonetheless.

**Comment by zkochan** [comment]
I think I'll implement it using sinopia instead.
