### ISSUE TITLE
Fixing EEXIST: file already exists, open '~/.pnpm-store/1/lock'

### ISSUE THREAD

**Issue by andreypopp** [rstacruz/pnpm#569]
This happens when you abort an installation (SIGINT) or installation fails.

I wonder if we can make it better. For example we can make lock a UNIX socket and listen on it. To check the lock we can try to connect to UNIX socket. If connection refused then we just remove the lock and proceed. Thoughts?

**Comment by zkochan** [comment]
What if we save the process id to the lockfile? In that case we can check whether the process that created the lockfile is running or not

**Comment by andreypopp** [comment]
Yeah, good idea too. Or we can use `proper-lockfile` which is being used by yarn — I didn't see such failures with yarn.

**Comment by zkochan** [comment]
Well, in that case I vote for `proper-lockfile`

**Comment by andreypopp** [comment]
Closing this as we use `proper-lockfile` now.
