### ISSUE TITLE
Use caching to minimise bandwidth usage / improve performance

### ISSUE THREAD

**Issue by misterbyrne** [rstacruz/pnpm#59]
To see whether it's worth exploring to achieve performance improvements, I quickly implemented something which would use the tarball from the .npm cache if present (and fall back to fetching from the server if not). It only improved the install time by about 7% :disappointed: (for quite a big project)

However, I then tried (something a little hackier) to force the package resolver to use npm's cached metadata if present (falling back to making a request to the registry if not). This improved the speed significantly:

Current master - no cache:

```
35.86s user 17.93s system 83% cpu 1:04.81 total
```

...cache

```
24.04s user 11.90s system 94% cpu 38.115 total
```

(BTW there does appear to be a slight performance regression in today's release - at the very end it's taking longer than before)

**Comment by rstacruz** [comment]
How'd you do it?

Yeah it'd take a little longer now... But not by so much. Is it really
noticable?

**Comment by misterbyrne** [comment]
I didn't push the branch :grimacing: 
It's hacky, but I'll push it when I get home from work so you can have a look.
I'll get timings on the regression too.

**Comment by rstacruz** [comment]
been wondering about this as well, and also wondering if it can share caches with `npm`.

**Comment by rstacruz** [comment]
> (BTW there does appear to be a slight performance regression in today's release - at the very end it's taking longer than before)

To explain:

1. We now throttle connections to a max of 16 at a time. You can get the old behavior with the (undocumented) switch of `--concurrency=9999`.
2. There is now some extra steps done after installing: specifically, modules will be linked into `node_modules/.store/node_modules`. This should take just a second or so.

**Comment by misterbyrne** [comment]
Good news! The performance regression isn't bad at all, around 3 secs - I don't know what happened before.

Also, it turns out that upping the concurrency had roughly the same effect as using locally cached meta-data. However, using locally cached tarballs does help quite a bit. Here are some timings.

- Normal v0.13.0 with concurrency 9999: around 28s - although varies wildly because we use a few large packages and the npm registry's transfer rate can change quite a lot  (2110 requests to the registry, 1696 unique URLs)
- Read everything from the cache: around 19s (no requests to the registry)
- Only use cached tarballs: around 22s (1344 metadata requests to the registry - 931 unique URLs for 631 packages)

There branch is here if you want to see what I did: https://github.com/rstacruz/pnpm/compare/master...misterbyrne:hack-use-npm-cache

**Comment by piranna** [comment]
I'm interested in this feature, if all the needed packages are in the npm cache, then there would be possible to do installs offline without needing of external tools like local proxies and similar things :-)

**Comment by rstacruz** [comment]
> metadata requests to the registry

would love to have this cached as well!

**Comment by patrickheeney** [comment]
+1. I was just going to attempt implementing this myself and noticed this issue. I have an app made up of a ton of decoupled modules that I was looking for a better way to manage. A vast majority of them share the same dependencies. A cache is critical to avoid network requests, keep it fast, offline installs, and keeping developers happy. 

Is there anything preventing @misterbyrne commit from merging?

**Comment by piranna** [comment]
Is there any update on this? It would be a killer-app feature... :-D

**Comment by vvo** [comment]
For what it's worth, I did an npm-pkgr https://github.com/vvo/npm-pkgr that agressively caches npm installs

**Comment by zkochan** [comment]
This is going to have a huge impact! If nobody started to work on it, probably this will be the next I will do after implementing update. Or even before it

**Comment by iamstarkov** [comment]
regarding caching, pnpm still needs to verify there are no newer versions out there

**Comment by zkochan** [comment]
yes, the cache will have lifetime and it can be short.

I currently use pnpm for installing dependencies in a monorepo, so it is executed many times. The packages have almost the same set of dependencies. Even though I use a shared storage, pnpm requests the package document for every installation.

**Comment by zkochan** [comment]
I added caching of HTTP requests. Caching of tarballs not done yet

**Comment by zkochan** [comment]
Caching of tarballs not needed anymore, because pnpm uses a global (machine) store. Every package@version is installed only once on a machine
