### ISSUE TITLE
Symlink error on Windows

### ISSUE THREAD

**Issue by zhoufenfens** [rstacruz/pnpm#6]
i use the pnpm-install,this is the error
![qq 201601291340431](https://cloud.githubusercontent.com/assets/3303836/12668072/138d274c-c68e-11e5-845e-9036bcc77ef6.png)

**Comment by rstacruz** [comment]
does it always happen?

sadly i'm a little clueless with windows, sorry :(

**Comment by zhoufenfens** [comment]
@rstacruz yes,i always happens,never succeed once time.

**Comment by rstacruz** [comment]
This symlinking strategy is crucial to how pnpm works. Sadly, I may just have to disable windows support altogether.

**Comment by stefanpenner** [comment]
Let me recommend the use of junctions as an alternative to symlinks on directories for Windows.

**Comment by rstacruz** [comment]
that makes sense! junctions work differently than symlinks though (symlinks are relative, eg, you can `ln .. parent` and move `parent` around and it'll always refer to the `..` of where it's placed to), so it isn't simply about replacing symlink() with junction().

Unless I'm mistaken in how junctions work, of course... haven't touched windows in a long while.

**Comment by stefanpenner** [comment]
Although symlinks are technically possible in newer Windows, the permission model results in fatally horrible UX. Avoid if possible

**Comment by pnorman** [comment]
I ran across this elsewhere (openstreetmap/iD#2574) for symlinks and git on Windows.

http://stackoverflow.com/questions/5917249/git-symlinks-in-windows says that NTFS junctions can be used and unlike NTFS symlinks, do not require elevated UAC permissions.

**Comment by louy2** [comment]
That's probably a UAC problem. Creating symlink in Windows always requires Admin.

**Comment by richardneililagan** [comment]
Confirmed that it works in an elevated `sh`-enabled prompt in Windows.

![image](https://cloud.githubusercontent.com/assets/705310/12675585/45e25978-c6c6-11e5-9944-b513f1b942c0.png)

**Comment by iamstarkov** [comment]
I think original problem is more related to permissions issue than symlink one

**Comment by proof** [comment]
ied has the same problem: https://github.com/alexanderGugel/ied/issues/35#issuecomment-160570170.

**Comment by rstacruz** [comment]
`npm link` defaults to junctions on windows.

https://github.com/npm/npm/blob/master/lib/utils/link.js#L41-L47

**Comment by rstacruz** [comment]
if anyone wants to take a stab at this, this can be fixed by going into `lib/force_symlink.js` and making a version of that that works with `process.platform === 'win32'`. Note that forceSymlink is typically done with relative paths, so that'll have to be normalized and accounted for.

**Comment by rstacruz** [comment]
Try it out again.

**Comment by davidshift** [comment]
Still seeing this in 0.17.0

**Comment by rstacruz** [comment]
exact same error?

**Comment by davidshift** [comment]
I'm seeing this:

` ! EPERM: operation not permitted, symlink 'C:\Users\peterd\.babun\cygwin\home\peterd\tmp\web-interface\node_modules\.tmp\308d0950-0416-473c-a52d-63854ee00f55' -> 'C:\Users\peterd\.babun\cygwin\home\peterd\tmp\web-interface\node_modules\.store\grunt-babel@5.0.3'`

**Comment by iamstarkov** [comment]
Maybe its basic permissions issue and doesn't relate to symlinking. That said can you try to grant access to your user to whole `C:\Users\peterd\.babun\cygwin\home\peterd\tmp` folder?

**Comment by davidshift** [comment]
This was a permission error and is resolved now! Thank you!

**Comment by stefanpenner** [comment]
some instructions for getting symlinks working (that seems to work for all users, unless some strange admin stuff) http://ember-cli.com/user-guide/#symlinks-on-windows

Ultimately though, this project is (or should) use junctions, as it merely needs to link dir, not dir + files.

**Comment by rstacruz** [comment]
I thought I enabled junctions... Let's see.
