### ISSUE TITLE
Remove `object-assign` and `bluebird` dependencies

### ISSUE THREAD

**Issue by davej** [rstacruz/pnpm#69]
Since pnpm is only compatible with node >= 4 anyway, why not use native promises and `Object.assign()`?

**Comment by rstacruz** [comment]
ahh... i think i found a bug on Promise.all that bluebird fixed, hence the need for bluebird. i'll have to investigate a little more on that.

I'd still like to keep bluebird as a devdependency though. its stack traces are super useful.

**Comment by rstacruz** [comment]
the `object-assign` makes sense!

actually, i've been thinking on whether it should support legacy node.js versions too... not sure on that. being able to use arrow functions really cleans up the source considerably.

**Comment by davej** [comment]
My $0.02 is to keep the source clean for the moment and use the ES6 features that are available. Could always do a babelified mirror for older versions of node if there's a demand for it.

**Comment by rstacruz** [comment]
actually i can probably do something like this:

```json
{
  "prepublish": /* convert lib/ to babel-ified versions */
  "postpublish": /* reset lib/ */
}
```

in which case it makes sense to keep bluebird/object-assign.

**Comment by davej** [comment]
Yup, I prefer the idea of doing this for a node 0.x fork though, and keeping the main lib unbabelified.

**Comment by davej** [comment]
Babel can polyfill Promises and `Object.assign` too by the way. Although perhaps it's best to keep bluebird for the reasons you mentioned.

**Comment by rstacruz** [comment]
> Babel can polyfill Promises and Object.assign too by the way

using `require('babel-polyfill')`, afaik. I'd rather keep that out :)

**Comment by davej** [comment]
> using require('babel-polyfill'), afaik. I'd rather keep that out :)

With Babel6, you selectively choosing the polyfills so it's no different that the `object-assign` polyfill currently being used. https://babeljs.io/docs/plugins/transform-object-assign/

**Comment by rstacruz** [comment]
okay, that's quite handy.

**Comment by davej** [comment]
Just going to lodge a :-1: on babelifying the main lib. :-)

I'd prefer to keep the node 0.x version as a fork. Babel adds a layer of abstraction (albeit lightweight) to debugging and stacktraces.

**Comment by davej** [comment]
I suppose sourcemaps negate that a little bit but I still prefer the idea of keeping the main lib without it.

**Comment by rstacruz** [comment]
> I'd prefer to keep the node 0.x version as a fork.

wouldn't a hard fork present a problem?

how about publishing a babelified version as "pnpm-legacy"?

**Comment by davej** [comment]
> how about publishing a babelified version as "pnpm-legacy"?

Yup, that's what I meant. Fork was probably a confusing word to use. :-)

**Comment by rstacruz** [comment]
oh there's also --retain-lines, how aboout that one?

**Comment by rstacruz** [comment]
also, there's an idea of something like

```js
install = isNodeVersion4orAbove
  ? require('lib/cmd/install')
  : require('lib.es5/cmd/install')
```

**Comment by davej** [comment]
> oh there's also --retain-lines, how aboout that one?

I'd prefer to just use sourcemaps over `--retain-lines`.

```js
install = isNodeVersion4orAbove
  ? require('lib/cmd/install')
  : require('lib.es5/cmd/install')
```

Are you bundling two versions of the lib in that case (es5 and es6)? My preference would still be to have a separate `pnpm-legacy` module.

**Comment by rstacruz** [comment]
yeah. my only concern with publishing a `pnpm-legacy` module is that it isn't putting the users ahead first: it's essentially pushing the burden on the user.

**Comment by rstacruz** [comment]
> I'd prefer to just use sourcemaps over --retain-lines, if it was between the two.

Does (modern) node.js support source maps?

**Comment by davej** [comment]
> Does (modern) node.js support source maps?

Yup

**Comment by rstacruz** [comment]
#73 now adds inline source maps as part of the babel experiment. No idea if it works, haha.

**Comment by davej** [comment]
> yeah. my only concern with publishing a pnpm-legacy module is that it isn't putting the users ahead first: it's essentially pushing the burden on the user.

Yeah, I look at it another way. You would be treating node >= 4 as a first class citizen, while still providing a path for Node 0.x users. The marketshare for 0.x will only continue to diminish over time. You can always decide to move the legacy version into core in the future if there's a demand... but it's much more difficult to move the other way because there will probably be people relying on 0.x support.

Just my 2 cents, obviously it's your module and your call though :-)

**Comment by davej** [comment]
Also, you can always console.log a descriptive error message telling users to install `pnpm-legacy` when run on node 0.x. It's not much of a roadblock really.

**Comment by rstacruz** [comment]
on the other hand it'd cause fragmentation. keep in mind the CLI isn't the only way to consume `pnpm`—say, if ember-cli were to add pnpm support, they'd likely opt to use `pnpm-legacy` instead.

**Comment by davej** [comment]
Yeah, but the nice thing is that `pnpm-legacy` would be phased out over time. There may be a demand for it now but perhaps not so much in a couple of years time. And when demand goes away then you're not left in a position where you still need to transpile to support 1% of the user-base who are still using node 0.x.

Anyway, I see pros and cons both ways and my opinion is more of a personal preference really :-)

**Comment by rstacruz** [comment]
I couldnt get the object-assign transform to work, btw. bummer
