### ISSUE TITLE
Module name on npm

### ISSUE THREAD

**Issue by davej** [rstacruz/pnpm#70]
The current module name `pnpm.js` is a bit funky. I wonder would @crcn be interested in releasing the `pnpm` name?

**Comment by crcn** [comment]
Yep, I'd be happy to transfer over the name. Want me to go ahead and run `npm owner add rstacruz pnpm`?

**Comment by rstacruz** [comment]
yes please!

hi @crcn!

**Comment by crcn** [comment]
Done! Feel free you run `npm owner remove crcn pnpm`.

**Comment by rstacruz** [comment]
this literally just came into my inbox 5 seconds after i published 0.15.0. haha. thanks @crcn!

curious: what was the old pnpm for?

**Comment by rstacruz** [comment]
published now as 0.16.0. I've added a deprecation on the old package as well.

It seems npmjs.com (the website) is taking a while to update though... https://www.npmjs.com/package/pnpm

**Comment by crcn** [comment]
Looks like it's updated for me @rstacruz. `pnpm` hasn't been used in a few years - it was originally built to help setup private npm servers, but that problem is a whole can of worms, so I decided not to pursue the project.

**Comment by rstacruz** [comment]
I also did `npm owner remove architectd pnpm` (it was on your other username).
