### ISSUE TITLE
getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443

### ISSUE THREAD

**Issue by sc0rp10** [rstacruz/pnpm#8]
When I executed `pnpm install` I've got random error like
```
getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
GET registry.npmjs.org/mime-types/~2.1.8
```
But if I run `curl https://registry.npmjs.org/mime-types/~2.1.8` I see expected json output.
With each command run library changes.

**Comment by gillstrom** [comment]
Related with #7.
