### ISSUE TITLE
Implementing scoped modules

### ISSUE THREAD

**Issue by indexzero** [rstacruz/pnpm#9]
As a new developer to the code base I was hoping you could give some foot notes on where I should start looking if I wanted to implement scoped module support.

**Comment by rstacruz** [comment]
oh gosh this may or may not be that simple, haha. normal package resolutions are done this way: (`lib/resolve.js`):

```
pnpm install lodash@^4.0.0
> GET https://registry.npmjs.org/lodash/^4.0.0
> get `dist.tarball` from its response
```

but scoped resolutions must be done this way:

```
pnpm install @rstacruz/tap-spec@^4.0.0
> GET https://registry.npmjs.org/@rstacruz%40tap-spec
> get `versions` from its response
> find the version that matches `^4.0.0` using `semver.maxSatisfies()`
> get `dist.tarball` from it
```

they should also be stored in the store without a `/` to maintain true flatness. This is because symlinks in node_modules inside it assume the store is at `../../`. So that'd be:

```
node_modules/.store/@rstacruz--tap-spec@4.0.0
```


Apart from this, there might be some symlinking voodoo that may come out of symlinking `node_modules/.store/@rstacruz--tap-spec@4.0.0` -> `@rstacruz/tap-spec`, but I haven't given that part enough thought just yet.

**Comment by indexzero** [comment]
The registry part of this should be relatively straight forward. Let me take a stab at that and see how I feel :smile:

**Comment by indexzero** [comment]
Got started on this, but some early debugging revealed that the semver ranges from the registry actually work.

```
$ curl https://registry.npmjs.org/@rstacruz%2Ftap-spec/%5E4.0.0 -s | json
{
  "name": "@rstacruz/tap-spec",
  "version": "4.1.1",
  "description": "Formatted TAP output like Mocha's spec reporter",
  "main": "index.js",
  "scripts": {
    "test": "echo 'Tests are out of date. Not running until fixed.'"
  },
```

So then there would be no need to add extra logic to `resolve.js`.

**Comment by rstacruz** [comment]
YAY lets  do that

**Comment by rstacruz** [comment]
btw there's `pnpm install @rstacruz/tap-spec --debug`

**Comment by rstacruz** [comment]
```
pnpm:http https://registry.npmjs.org/@rstacruz%2Ftap-spec/latest +4ms

Response code 401 (Unauthorized)
GET registry.npmjs.org/@rstacruz%2Ftap-spec/latest
```
:(

**Comment by rstacruz** [comment]
`pnpm install @rstacruz/tap-spec@'*' --debug` works though. the only thing stopping it is the need to mkdir `.store/@rstacruz`.

```
Error: Error: ENOENT: no such file or directory, rename '/xxx/node_modules/.tmp/5d54904e-5ef9-4acf-bd99-8781b3e53f0b' -> '/xxx/node_modules/.store/@rstacruz/tap-spec@4.1.1'
```

**Comment by rstacruz** [comment]
edit:

> they should also be stored in the store without a / to maintain the "flatness" of .store. This is because symlinks in node_modules inside it assume the store is at ../../. So that'd be:

>     node_modules/.store/@rstacruz--tap-spec@4.0.0  # ✓ ok
>     node_modules/.store/@rstacruz/tap-spec@4.0.0   # ✗ bad

don't listen to me on this. i just tested it and it's fine.

```
mkdir -p node_modules/@rstacruz
pnpm install @rstacruz/tap-spec@'*' --debug
```

the only thing missing is a way to resolve `latest` in a scoped package.

**Comment by rstacruz** [comment]
Okay, we now have this. this works:

```
pnpm install @rstacruz/tap-spec@*
```

but this doesn't:

```
pnpm install @rstacruz/tap-spec
```

**Comment by rstacruz** [comment]
As a workaround **for now**, `pnpm install @rstacruz/deku` is now an alias for  `pnpm install @rstacruz/deku@*` (which should actually be `...@latest`). It achieves *more or less* the same effect.

**Comment by indexzero** [comment]
@rstacruz I'm satisfied with the support of scoped modules. Going to close this.

**Comment by rstacruz** [comment]
So am I, good work!

**Comment by rstacruz** [comment]
Oh there's something that doesn't quite work yet that's important... Exact
versions.

pnpm i @rstacruz/tap-spec@4.1.1

**Comment by onbjerg** [comment]
Still doesn't work.

``pnpm i --save-dev @kadira/storybook`` fails with some symlink stuff
