### ISSUE TITLE
node_modules/.bin/ should contain bin links from all the nested packages

### ISSUE THREAD

**Issue by deepsweet** [rstacruz/pnpm#96]
I know that this may sound controversial but at least native npm cli is doing so and this behavior should not be broken.

**Comment by rstacruz** [comment]
This was discussed on #58. does it break your workflow?

**Comment by deepsweet** [comment]
well, it's more a minor inconvenience than a real problem in my workflow. I just wanted to make sure that relying on flatten `node_modules/.bin/` was not a good idea. feel free to close this if supporting this behavior is not in your plans, looks like I'll change my workflow in anyway.

**Comment by rstacruz** [comment]
there are many npm3 things that would be difficult to support that it's easier for pnpm to achieve npm2-like-ness.

**Comment by zkochan** [comment]
currently this seems like we wont fix, but I added a special label for it in case we'll want to reconsider it in the future

**Comment by zkochan** [comment]
@deepsweet we released the possibility to install dependencies flat in [v0.42.0](https://github.com/rstacruz/pnpm/releases/tag/v0.42.0) (under the next dist-tag for now). This is solved as well by the `--flat-tree` option
